# Generated by Django 2.0.1 on 2018-01-17 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donnees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donnees', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='DonneesSaisies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_utilise', models.DateField(verbose_name='Date Utilisé')),
                ('somme', models.FloatField()),
                ('categorie_donneesSaisies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Moyen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyen', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='donneessaisies',
            name='institution_donneesSaisies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.Institution'),
        ),
        migrations.AddField(
            model_name='donneessaisies',
            name='moyen_donneesSaisies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.Moyen'),
        ),
        migrations.AddField(
            model_name='donnees',
            name='moyen_donnees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projets.Moyen'),
        ),
    ]
