# Generated by Django 2.0.1 on 2018-01-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContratProfessionel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date début')),
                ('date_fin', models.DateField()),
                ('titre', models.CharField(max_length=50)),
                ('lieu', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=30)),
                ('commentaire', models.TextField(max_length=300)),
                ('type_contrat', models.CharField(max_length=20, verbose_name='type de contrat')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContratUniversitaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date début')),
                ('date_fin', models.DateField()),
                ('titre', models.CharField(max_length=50)),
                ('lieu', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=30)),
                ('commentaire', models.TextField(max_length=300)),
                ('specialite', models.CharField(blank=True, max_length=50, verbose_name='spécialite')),
                ('parcours', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
